# Generated by Django 6.1 on 2026-09-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahasiswa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
