# Generated by Django 6.1 on 2026-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('highlight', models.CharField(max_length=255)),
                ('logo_path', models.CharField(max_length=255)),
            ],
        ),
    ]
